## Notebook for computing buffers

```{r}
source('utils.R')
library(leaflet)
library(mapview)
```

#### Load the data
```{r}
db <- readRDS("./data/master_db_filtered.rds")
```

#### Preparing the data for computing buffers

```{r}
db <- sample_n(db, 4000)
db$latitud <- as.numeric(db$latitud)
db$longitud <- as.numeric(db$longitud)

```

```{r}
calc_buffers <- function(df, radious){
  "Calculates buffers for schools"
  db_sp <- db # create a df to be converted to a spatial object
  ## projections
  unproj <- CRS("+proj=longlat +datum=WGS84")
  proj <- CRS("+init=epsg:6370")  
  coordinates(db_sp) <- c(x="longitud", y="latitud") 
  proj4string(db_sp) <- unproj  
  db_sp <- spTransform(db_sp, proj) 
  ## calculate buffers
  buffers <- gBuffer(db_sp, width=1000) 
  db$buffer <- as.character(over(db_sp, disaggregate(buffers)))
  db <- db %>% arrange(as.numeric(buffer))
  # for graphing buffers
  buffers_proj <- spTransform(buffers, '+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs')
  # return both df and spdf for graph maps
  buffers_outs <- list("df_buffers"=db, "buffers_proj"=buffers_proj)
  
  return(buffers_outs)
}

buff_mock <- calc_buffers(db, 3000)


df_buffers <- buff_mock$df_buffers
proj_buffers <- buff_mock$buffers_proj


```

```{r}
ncolors <- max(df_buffers$buffer)
pal <- colorNumeric(c("red", "green", "blue"), 1:ncolors)
colors_test <-pal(seq(1,99,1))

df_buffers
library(leaflet)
library(htmltools)
leaflet() %>%
  
    addProviderTiles(providers$Stamen.TonerLite,
                      options = providerTileOptions(noWrap = TRUE)) %>%
      addTiles() %>% 
      addPolygons(data=proj_buffers, weight = 2, fillColor = colors_test) %>% 
      addCircleMarkers(data=df_buffers, ~longitud, ~latitud, color = "red", stroke = FALSE, fillOpacity = 0.5,radius=2,
                       label = ~htmlEscape(paste("CCT:", cct, "Buffer", buffer)))
```


```{r}
    m <- leaflet() %>%
      addProviderTiles(providers$Stamen.TonerLite,
                       options = providerTileOptions(noWrap = TRUE)
      ) %>%
      addTiles() %>% 
      addCircles(data = db, lng=~longitud, lat=~latitud, radius=3, weight = 1, color="#E74B52") 
    # adds menu for visualization
    m %>% setView(0,0,3)
    esri <- grep("^Esri", providers, value = TRUE)
    for (provider in esri) {
      m <- m %>% addProviderTiles(provider, group = provider)
    }
    m %>%
      addLayersControl(baseGroups = names(esri),
                       options = layersControlOptions(collapsed = FALSE)) %>%
      addMiniMap(tiles = esri[[1]], toggleDisplay = TRUE,
                 position = "bottomleft") %>%
      htmlwidgets::onRender("
    function(el, x) {
      var myMap = this;
      myMap.on('baselayerchange',
        function (e) {
          myMap.minimap.changeLayer(L.tileLayer.provider(e.name));
        })
    }")
```

#### Function for generating buffers
```{r}

```


#### Saving the generated buffers
```{r}

```

#### Visualizing buffers in maps

```{r}

```

