---
title: "network_visualization"
output: html_document
---

```{r}
source('utils.R')
library(tidyverse)
library(tidygraph)
library(ggraph)
library(igraphdata)
```

#### Load the data
```{r}
db <- readRDS("./data/master_db_filtered.rds")
df <- df_buffers
```

#### Preparing the data for computing buffers
```{r}
set.seed(1992)
db <- sample_n(db, 15000)
db$latitud <- as.numeric(db$latitud)
db$longitud <- as.numeric(db$longitud)
```

#### Function for generating buffers
```{r}
# call our function for calculating buffers
buff_test <- calc_buffers(db, 6000)
# extract relevant elements
df_buffers <- buff_test$df_buffers
proj_buffers <- buff_test$buffers_proj
```


#### Saving the generated buffers
```{r}
saveRDS(df_buffers, "./data/df_ch_df_test_15k_6km.rds")
saveRDS(proj_buffers, "./data/proj_buffers_test_15k_6km.rds")
# df_buffers <-readRDS("./data/df_ch_df_test_15k_6km.rds")
# proj_buffers <- readRDS("./data/proj_buffers_test_15k_6km.rds")
```

#### Calculate convex hulls
```{r}
ch_df <- calc_convexhulls(df_buffers)
saveRDS(ch_df, "./data/df_ch_df_test_15k_6km.rds")
```

## Unions first attempt
```{r}
unions <- st_union(ch_df$ch_polygons) %>%  st_sf()
saveRDS(unions, "./data/df_unions_test_16k_6km.rds")
```


```{r}
path <- "./data/agregados/"
# df_sec <- read_csv(paste0(path, "agregado_dist_sec_v2.csv"))
# saveRDS(df_sec, paste0(path, "agregado_dist_sec_v2.rds"))
# original
df <- readRDS(paste0(path, paste0(path, "agregado_dist_sec_v2.rds")))

```

```{r}
nodos <- df_buffers %>% rename(grupo=buffer)
nodos %>% group_by(grupo) %>%  summarise(n=n()) %>% arrange(-n)
```


```{r}
nodos <- df_buffers %>% rename(name=cct, lat=latitud, lon=longitud, grupo=buffer)
df <- readRDS("./data/agregados/agregado_dist_sec_v2.rds")

relations<-get_relations(nodos, df)
select_relations <- get_select_relations(nodos, current_group)
select_nodos <- get_select_nodos(select_relations,current_group)
# 
current_group <- 14

select_relations <- get_select_relations(nodos, current_group)
select_nodos <- get_select_nodos(select_relations,current_group)

school_network <- graph_from_data_frame(select_relations, directed=FALSE, vertices=select_nodos)
is_weighted(school_network)

fc <- cluster_fast_greedy(school_network)
algorithm <- str_replace(algorithm(fc), " ", "_")
select_nodos <- save_subgroups(fc, select_nodos, algorithm, current_group)

get_centrality_stats(school_network, current_group)


fc <- cluster_fast_greedy(school_network)
algorithm <- str_replace(algorithm(fc), " ", "_")
select_nodos <- save_subgroups(fc, select_nodos,
                               algorithm, current_group)

save_map(select_nodos,algorithm, current_group)
get_stats_group(select_nodos, algorithm, current_group)
get_community_stats(fc) 
```

```{r}
test <- graph_mapnetworks(select_nodos, select_relations)
vert <- test$verts
edges <- test$edges
network <- test$network
```



#### Big map with layers
```{r}
# df_buffers <- df_buffers %>%  mutate(estado=substr(cct, 1, 2))
# df_buffers
```

```{r}
#school icons
icons <- awesomeIcons(
  icon = "graduation-cap", library = "fa",
  markerColor = "green"
)


  leaflet() %>%
  # Schools
    addTiles() %>% 
    addAwesomeMarkers(data=df_buffers, ~longitud, ~latitud,group = "Schools",
                     clusterOptions = markerClusterOptions(),
                     label = ~htmlEscape(paste("CCT:", cct, "Buffer", buffer)),
                     icon=icons
                )  %>% 
  # convexhulls
  addPolygons(data=ch_df$ch_polygons, group = "Convex Hulls",
              stroke = FALSE, smoothFactor = 0.2, fillOpacity = 0.2, fillColor="red") %>% 
  # Buffers
  addPolygons(data=proj_buffers, weight = 3, fillColor = "green", group = "Buffers") %>%
  # Unions
  addPolygons(data=unions, weight = 3, fillColor = "yellow", group = "Convex Hull Unions") %>% 
  # networks
  addCircles(data=vert, radius=3, weight = 3, color="black", group = "Networks") %>%
    addPolylines(data=edges, weight = 1*network$edges$freq, color="black", group = "Networks") %>%
  # Additionals
    # Layers control
    addLayersControl(
    # baseGroups = c("OSM (default)", "Toner", "Toner Lite"),
    overlayGroups = c("Schools", "Buffers", "Convex Hulls", "Convex Hull Unions", "Networks"),
    options = layersControlOptions(collapsed = FALSE)
  ) %>% 
  clearBounds()
```










